import type { CatalogItem } from "./types";

// REAL Petz catalog — 78 items scraped from petz.com.br search pages on
// 2026-06-30 (name + price). unitPrice is the real Petz cost; the 10% markup is applied
// downstream. Pet supplies only (no antiparasitic medication). Starter catalog — expand
// by re-scraping more pet search terms.
export const PETZ_CATALOG: CatalogItem[] = [
  { sku: "PETZ-001", name: "Ração Golden Special para Cães Adultos Sabor Frango e Carne", unitPrice: 204.9, unit: "un", category: "pet" },
  { sku: "PETZ-002", name: "Ração Premier Nutrição Clínica Hipoalergênico para Cães de Médio e Grand", unitPrice: 379.9, unit: "un", category: "pet" },
  { sku: "PETZ-003", name: "Ração Golden Fórmula Para Cães Adultos de Porte Pequeno Sabor Carne e Ar", unitPrice: 174.9, unit: "un", category: "pet" },
  { sku: "PETZ-004", name: "Ração Premier Fórmula para Cães Adultos de Raças Grandes e Gigantes", unitPrice: 259.9, unit: "un", category: "pet" },
  { sku: "PETZ-005", name: "Ração Golden Power Training para Cães Adultos Sabor Frango e Arroz 15kg", unitPrice: 179.9, unit: "un", category: "pet" },
  { sku: "PETZ-006", name: "Ração Golden Fórmula para Cães Senior Sabor Frango e Arroz 15kg", unitPrice: 186.9, unit: "un", category: "pet" },
  { sku: "PETZ-007", name: "Ração Premier Nutrição Clínica Hipoalergênico para Cães de Pequeno Porte", unitPrice: 99.9, unit: "un", category: "pet" },
  { sku: "PETZ-008", name: "Ração Seca Royal Canin Veterinary Diet Hypoallergenic Small Dog", unitPrice: 177.99, unit: "un", category: "pet" },
  { sku: "PETZ-009", name: "Ração Golden Special para Gatos Castrados Sabor Frango e Carne", unitPrice: 66.9, unit: "un", category: "pet" },
  { sku: "PETZ-010", name: "Ração Úmida Premier Gourmet Para Gatos sabor Atum e Arroz integral 70g", unitPrice: 7.99, unit: "un", category: "pet" },
  { sku: "PETZ-011", name: "Ração Úmida Royal Canin Pedaços ao Molho Sachê para Gatos Adultos Castrados", unitPrice: 9.9, unit: "un", category: "pet" },
  { sku: "PETZ-012", name: "Ração Golden Special para Gatos Adultos Sabor Frango e Carne", unitPrice: 59.9, unit: "un", category: "pet" },
  { sku: "PETZ-013", name: "Ração GranPlus Choice para Gatos Adultos Sabor Frango e Carne 10,1kg", unitPrice: 152.9, unit: "un", category: "pet" },
  { sku: "PETZ-014", name: "Ração Premier Nutrição Clínica Obesidade para Gatos Adultos 1,5kg", unitPrice: 104.9, unit: "un", category: "pet" },
  { sku: "PETZ-015", name: "Ração Fórmula Natural Fresh Meat para Gatos Adultos Castrados", unitPrice: 77.99, unit: "un", category: "pet" },
  { sku: "PETZ-016", name: "Biscoito Premier Cookie para Cães Adultos Sabor Frutas Vermelhas", unitPrice: 19.99, unit: "un", category: "pet" },
  { sku: "PETZ-017", name: "Biscoito Premier Cookie para Cães Adultos de Raças Pequenas 250g", unitPrice: 19.99, unit: "un", category: "pet" },
  { sku: "PETZ-018", name: "Biscoitos Fórmula Natural Dog Biscuits para Cães Adultos", unitPrice: 16.99, unit: "un", category: "pet" },
  { sku: "PETZ-019", name: "Biscoito Premier Cookie para Cães Filhotes Sabor Frutas Vermelhas", unitPrice: 19.99, unit: "un", category: "pet" },
  { sku: "PETZ-020", name: "Biscoito Premier Cookie Fit para Cães Adultos Sabor Frango com Banana", unitPrice: 19.99, unit: "un", category: "pet" },
  { sku: "PETZ-021", name: "Petisco Selections Peito de Frango Desidratado para Cães", unitPrice: 8.99, unit: "un", category: "pet" },
  { sku: "PETZ-022", name: "Bifinho Selections For Pets Strip Mini para Cães Sabor Carne 500g", unitPrice: 33.99, unit: "un", category: "pet" },
  { sku: "PETZ-023", name: "Biscoito Nutrifresh Natural Sabor Camomila Maracujá e Ervilha para Cães", unitPrice: 13.99, unit: "un", category: "pet" },
  { sku: "PETZ-024", name: "Areia Higiênica Cansei de Ser Gato Biodegradável Grãos Finos", unitPrice: 39.99, unit: "un", category: "pet" },
  { sku: "PETZ-025", name: "Areia Higiênica Cansei de Ser Gato Biodegradável Grãos Médios", unitPrice: 39.99, unit: "un", category: "pet" },
  { sku: "PETZ-026", name: "Granulado Higiênico Petz Biodegradável Milho e Mandioca Grãos Finos", unitPrice: 59.99, unit: "un", category: "pet" },
  { sku: "PETZ-027", name: "Areia Higiênica Fresh Milho e Mandioca para Gatos 3kg", unitPrice: 44.99, unit: "un", category: "pet" },
  { sku: "PETZ-028", name: "Areia Petz Ultra Absorção para Gatos 4kg", unitPrice: 54.99, unit: "un", category: "pet" },
  { sku: "PETZ-029", name: "Granulado Higiênico Petz Biodegradável Cereais para Gatos 3kg", unitPrice: 44.99, unit: "un", category: "pet" },
  { sku: "PETZ-030", name: "Areia Higiênica Fresh Grãos Finos Perfumada para Gatos", unitPrice: 19.99, unit: "un", category: "pet" },
  { sku: "PETZ-031", name: "Areia Higiênica Fresh Grãos Médios para Gatos", unitPrice: 15.99, unit: "un", category: "pet" },
  { sku: "PETZ-032", name: "Areia Higiênica Fresh Grãos Finos para Gatos", unitPrice: 17.99, unit: "un", category: "pet" },
  { sku: "PETZ-033", name: "Areia Higiênica Fresh Sílica Cristal para Gatos 1,6kg", unitPrice: 39.99, unit: "un", category: "pet" },
  { sku: "PETZ-034", name: "Tapete Higiênico Petz para Cães Superabsorvente 30 Unidades", unitPrice: 111.99, unit: "un", category: "pet" },
  { sku: "PETZ-035", name: "Super Secão Tapete Higiênico para Cachorro 30 un", unitPrice: 117.99, unit: "un", category: "pet" },
  { sku: "PETZ-036", name: "Super Secão Tapete Higiênico para Cachorro 14 un", unitPrice: 69.99, unit: "un", category: "pet" },
  { sku: "PETZ-037", name: "Tapete Higiênico Zee.Pad Preto para Cães Zee.Dog", unitPrice: 26.99, unit: "un", category: "pet" },
  { sku: "PETZ-038", name: "Tapete Higiênico Zee.Pad para Cães com 30 Unidades Branco Zee.Dog", unitPrice: 129.99, unit: "un", category: "pet" },
  { sku: "PETZ-039", name: "Tapete Higiênico Super Secão Max Citrus Slim para Cães", unitPrice: 103.99, unit: "un", category: "pet" },
  { sku: "PETZ-040", name: "Tapete Higiênico Super Secão Max Slim para Cães", unitPrice: 46.99, unit: "un", category: "pet" },
  { sku: "PETZ-041", name: "Tapete Higiênico Petix Supersecão Max Citrus 30 Unidades", unitPrice: 129.99, unit: "un", category: "pet" },
  { sku: "PETZ-042", name: "Shampoo Dermatológico Virbac Hexadene Spherulites para Cães e Gatos", unitPrice: 262.99, unit: "un", category: "pet" },
  { sku: "PETZ-043", name: "Shampoo Dermatológico Virbac Sebolytic SIS para Cães 250ml", unitPrice: 250.99, unit: "un", category: "pet" },
  { sku: "PETZ-044", name: "Shampoo Dermatológico Virbac Allermyl SIS para Cães", unitPrice: 171.5, unit: "un", category: "pet" },
  { sku: "PETZ-045", name: "Shampoo Fresh Care Peles Sensíveis para Cães 500ml", unitPrice: 21.99, unit: "un", category: "pet" },
  { sku: "PETZ-046", name: "Hidrapet Shampoo para Cães e Gatos", unitPrice: 141.99, unit: "un", category: "pet" },
  { sku: "PETZ-047", name: "Shampoo Fresh Care 5 em 1 para Cães 500ml", unitPrice: 21.99, unit: "un", category: "pet" },
  { sku: "PETZ-048", name: "Shampoo Agener União Dermogen para Cães e Gatos", unitPrice: 87.99, unit: "un", category: "pet" },
  { sku: "PETZ-049", name: "Shampoo Virbac Phisioderm Pele Sensível para Cães e Gatos", unitPrice: 168.5, unit: "un", category: "pet" },
  { sku: "PETZ-050", name: "Shampoo Fresh Care Neutro para Cães 500ml", unitPrice: 21.99, unit: "un", category: "pet" },
  { sku: "PETZ-051", name: "Coleira Antipulgas e Carrapatos Seresto para Cães acima de 8kg", unitPrice: 238.99, unit: "un", category: "pet" },
  { sku: "PETZ-052", name: "Brinquedo Spike Macaco de Pelúcia para Cães", unitPrice: 34.99, unit: "un", category: "pet" },
  { sku: "PETZ-053", name: "Brinquedo Chalesco Macaco Pelúcia Marrom para Cães", unitPrice: 34.99, unit: "un", category: "pet" },
  { sku: "PETZ-054", name: "Brinquedo Tamanduá de Pelúcia Petz para Cães", unitPrice: 79.99, unit: "un", category: "pet" },
  { sku: "PETZ-055", name: "Brinquedo Zee.Dog Banana para Cães", unitPrice: 89, unit: "un", category: "pet" },
  { sku: "PETZ-056", name: "Brinquedo Zee.Dog Nylon Wishbone para Cães", unitPrice: 129, unit: "un", category: "pet" },
  { sku: "PETZ-057", name: "Brinquedo Spike Elefante Long Puppet para Cães", unitPrice: 59.99, unit: "un", category: "pet" },
  { sku: "PETZ-058", name: "Brinquedo Spike Bicho Preguiça para Cães", unitPrice: 34.99, unit: "un", category: "pet" },
  { sku: "PETZ-059", name: "Brinquedo Zee.Dog Nylon Tripod para Cães", unitPrice: 159, unit: "un", category: "pet" },
  { sku: "PETZ-060", name: "Brinquedo Chalesco Macaco Copa Brasil Para Cães", unitPrice: 39.99, unit: "un", category: "pet" },
  { sku: "PETZ-061", name: "Brinquedo Zee.Dog Mr. X para Cães", unitPrice: 129, unit: "un", category: "pet" },
  { sku: "PETZ-062", name: "Osso Spike Orelha Bovina para Cães", unitPrice: 8.59, unit: "un", category: "pet" },
  { sku: "PETZ-063", name: "Osso Selections Orelha Suína Desidratada para Cães", unitPrice: 9.99, unit: "un", category: "pet" },
  { sku: "PETZ-064", name: "Osso PetTreats Orelha Bovina Natural para Cães 1 unidade", unitPrice: 9.99, unit: "un", category: "pet" },
  { sku: "PETZ-065", name: "Osso 3 Traqueia com 12 Unidades para Cães Natural Farm", unitPrice: 25.99, unit: "un", category: "pet" },
  { sku: "PETZ-066", name: "Osso PetTreats Orelha Suína Bacon para Cães 1 unidade", unitPrice: 10.99, unit: "un", category: "pet" },
  { sku: "PETZ-067", name: "Osso PetTreats Mordidinhas de Frango para Cães 100g", unitPrice: 17.99, unit: "un", category: "pet" },
  { sku: "PETZ-068", name: "Osso Casco Bovino com 6 Unidades para Cães Natural Farm", unitPrice: 29.99, unit: "un", category: "pet" },
  { sku: "PETZ-069", name: "Osso PetTreats Tubinho de Carne para Cães 3 unidades", unitPrice: 13.99, unit: "un", category: "pet" },
  { sku: "PETZ-070", name: "Osso PetTreats Churrasquinho para Cães 1 unidade", unitPrice: 38.99, unit: "un", category: "pet" },
  { sku: "PETZ-071", name: "Osso PetTreats Casco Bovino para Cães", unitPrice: 10.99, unit: "un", category: "pet" },
  { sku: "PETZ-072", name: "Comedouro Ergonômico Fuzz Bege para Gatos 390ml", unitPrice: 44.99, unit: "un", category: "pet" },
  { sku: "PETZ-073", name: "Comedouro Cansei de Ser Gato Alto de Madeira Duplo", unitPrice: 224.99, unit: "un", category: "pet" },
  { sku: "PETZ-074", name: "Suporte para Comedouro Cansei de Ser Gato 2 Alturas", unitPrice: 149.99, unit: "un", category: "pet" },
  { sku: "PETZ-075", name: "Comedouro Zee.Dog Bowl Soft Blue para Cães", unitPrice: 229, unit: "un", category: "pet" },
  { sku: "PETZ-076", name: "Comedouro Zee.Dog Bowl Gotham para Cães", unitPrice: 229, unit: "un", category: "pet" },
  { sku: "PETZ-077", name: "Comedouro Zee.Dog Melamina Terranova para Cães", unitPrice: 99, unit: "un", category: "pet" },
  { sku: "PETZ-078", name: "Comedouro Zee.Dog Tuff Pequeno Stripes Clay para Cães", unitPrice: 199, unit: "un", category: "pet" }
];
